DirectoryPath: "tyk-docs/public"
IgnoreAltMissing: true
IgnoreAltEmpty: true
IgnoreDirectoryMissingTrailingSlash: true
CheckInternalHash: false
IgnoreEmptyHref: true
CheckExternal: true
RedirectLimit: 5

TestFilesConcurrently: true
LogLevel: 3
IgnoreURLs:
  - "apps"
  - "/^https:\/\/github\.com\/TykTechnologies\/tyk-docs\/edit\/.*/"
