name: Index update
on: 
  workflow_dispatch:

jobs:
  index:
    runs-on: ubuntu-latest
    services:
      indexer:
        image: algolia/docsearch-scraper
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          API_KEY: ${{ secrets.ALGOLIA_APP_ID }}
          CONFIG: ${{ secrets.ALGOLIA_CONFIG }}
    steps:
      - name: Wait for index to compete
        run: echo "Finished"
