name: Index update
on: 
  workflow_dispatch:

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - name: Index
        run: docker run -i -e APPLICATION_ID=${{ secrets.ALGOLIA_APPLICATION_ID }} -e API_KEY=${{ secrets.ALGOLIA_APP_ID }} -e "CONFIG=${{ secrets.ALGOLIA_CONFIG }}" algolia/docsearch-scraper

