name: Check for missing links in menu.yaml
on:
  # pull_request:
  push:
    branches:
      - simon-gh-action-for-menu-link-checks

jobs:
  check_menu_links:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'
          extended: true
      - uses: actions/checkout@v3 # download tyk-docs repo
        name: clone tyk-docs
        # with:
        #   path: ./tyk-docs
      - uses: actions/checkout@v3 # download the script repo
        name: clone tyk_libs
        with:
           repository: dcs3spp/tyk_libs
           path: ./tyk_libs

      - name: Prepare files to run script # the ghub action script
        run: |
          pwd
          ls
          cd ./tyk-docs
          ls
          hugo
          pwd
          ls ../
          cp data/menu.yaml ../tyk_libs/
          cp public/urlcheck.json ../tyk_libs/
      - name: Run script to check for missing links in menu.yaml
        run: |
          cd ../tyk_libs
          make find_missing_links
